- name: Remove postgres repository
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: absent

- name: Uninstall libicu
  yum:
    name: https://rpmfind.net/linux/centos/7.7.1908/os/x86_64/Packages/libicu-50.2-3.el7.x86_64.rpm
    state: absent

- name: Uninstall postgres
  yum:
    name: postgresql11-server
    state: absent
